apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
          image: nuvalence/sample
          name: service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
