version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!@#%123
    ports:
      - 5432:5432
  service:
    image: nuvalence/sample
    environment:
      SPRING_PROFILES_ACTIVE: test
    ports:
      - 8080:8080
    depends_on:
      - db
