management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres!@#%123
  flyway:
    url: jdbc:postgresql://db:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
