apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{- include "sample-spring-postgres-app.fullname" . -}}
  name: {{- include "sample-spring-postgres-app.fullname" . -}}
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: {{- include "sample-spring-postgres-app.fullname" . -}}
