apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: service
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: service
