apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      serviceAccountName:  {{ include "sample-spring-postgres-app.serviceAccountName" . }}
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
          image: {{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}
          name: service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
